#! /bin/zsh

. ~/dunnit/dunnit.zsh

cd ~/dunnit

git fetch

if [[ $(git rev-parse HEAD) != $(git rev-parse '@{u}') ]]; then
    print 'Update available!'
    ans=$($alerter  \
	 	  -timeout 300 \
		  -actions 'Upgrade' \
		  -closeLabel 'No thanks' \
                  -title "Dunnit Software Update" \
		  -subtitle "There is a new update available." \
		  -message 'Would you like to install it now?' \
		  -sound 'Glass')
    if [[ $ans == 'Upgrade' ]]; then
	pkill dunnit-menu
	git rebase
	launchctl unload dunnit.plist dunnit-eod.plist dunnit-swupdate.plist
	launchctl load -w dunnit.plist dunnit-eod.plist dunnit-swupdate.plist
	./dunnit-menu
    fi
fi
