#! /bin/zsh

. ~/dunnit/dunnit.zsh

wk=${1?provide week}

files=( ~/dunnit/log/$yr/${wk}*/ledger*.txt )

smz() { gsed -nr "s/\[..:..\] $1 /- /p" $files }

print -- "% $username"
print -- "% Week $wk\n"

print '## Summaries\n'
# for f in $files; do
#     # pcre2grep -hM '## Summary\n\n(.|\n)*?\n\n' $f | gsed -n '3,$p'
# done
# gsed -nr 's/\[..:..\] DONE /- /p' $files
smz DONE

print -- '\n## Impacts\n'
smz IMPACT

print -- '\n## Sentiments\n'
smz SENTIMENT

print -- '\n## Productivity\n'
smz PRODUCTIVITY
