#! /bin/zsh

. ~/dunnit/dunnit.zsh

cd ~/dunnit

print 'Looking for recent version update of Dunnit.'
git fetch

if [[ $(git rev-parse HEAD) != $(git rev-parse '@{u}') ]]; then
    print 'Update available!'
    ans=$($alerter  \
	 	  -timeout 300 \
		  -appIcon ~/dunnit/dunnit-icon-purple.png \
		  -actions 'Upgrade' \
		  -closeLabel 'No thanks' \
                  -title "Dunnit Software Update" \
		  -subtitle "There is a new update available." \
		  -message 'Would you like to install it now?' \
		  -sound 'Glass')
    if [[ $ans == 'Upgrade' ]]; then
	print 'Shutting down running Dunnit instance.'
	pkill -af dunnit-menu
	git rebase
	# launchctl unload dunnit.plist dunnit-eod.plist dunnit-swupdate.plist dunnit-lunchhtime.plist
	print 'Reloading scheduled Dunnit prompt jobs.'
	launchctl load -w $dunnit_plists/dunnit*.plist
	./dunnit-menu
    fi
else
    terminal-notifier -title 'Dunnit Notice' \
		      -appIcon ~/dunnit/dunnit-icon-yellow.png \
		      -message 'No software update available at this time.'
fi
